Web/SayOnlinePanel.Web/Controllers/SurveysController.cs
namespace SayOnlinePanel.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;
    using SayOnlinePanel.Services.Data;
    using SayOnlinePanel.Web.ViewModels.Surveys;

    [Authorize(Roles = "Administrator")]
    public class SurveysController : Controller
    {
        private readonly ISurveyService surveyService;
        private readonly IWebHostEnvironment environment;

        public SurveysController(ISurveyService surveyService, IWebHostEnvironment environment)
        {
            this.surveyService = surveyService;
            this.environment = environment;
        }

        public IActionResult Create()
        {
            var viewModel = new CreateSurveyInputModel();
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateSurveyInputModel input, int id)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            try
            {
                await this.surveyService.CreateAsync(input, id);
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                return this.View(input);
            }

            this.TempData["Message"] = "Survey added successfully.";
            return this.Redirect("/Surveys/Surveys");
        }

        public IActionResult Surveys(int id = 1)
        {
            if (id <= 0)
            {
                return this.NotFound();
            }

            const int ItemsPerPage = 12;
            var viewModel = new SyrveysListViewModel
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = id,
                SurveysCount = this.surveyService.GetCount(),
                Surveys = this.surveyService.GetAll<SurveyInListViewModel>(id, ItemsPerPage),
            };
            return this.View(viewModel);
        }

        public IActionResult ById(int id)
        {
            var survey = this.surveyService.GetById<SingleSurveyViewModel>(id);
            return this.View(survey);
        }

        public IActionResult Edit(int id)
        {
            var inputModel = this.surveyService.GetById<EditSurveyInputModel>(id);
            return this.View(inputModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditSurveyInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            try
            {
                await this.surveyService.UpdateAsync(id, input);
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                return this.View(input);
            }

            return this.RedirectToAction(nameof(this.ById), new { id });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await this.surveyService.DeleteAsync(id);
            return this.RedirectToAction(nameof(this.Surveys));
        }
    }
}

Web/SayOnlinePanel.Web/Controllers/UserInfosController.cs
namespace SayOnlinePanel.Web.Controllers
{
    using System;
    using System.Globalization;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using SayOnlinePanel.Data;
    using SayOnlinePanel.Data.Models;
    using SayOnlinePanel.Services.Data;
    using SayOnlinePanel.Web.ViewModels.UserInfos;

    [Authorize]
    public class UserInfosController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ApplicationDbContext db;
        private readonly IUserInfosService userInfosService;

        public UserInfosController(UserManager<ApplicationUser> userManager, ApplicationDbContext db, IUserInfosService userInfosService)
        {
            this.userManager = userManager;
            this.db = db;
            this.userInfosService = userInfosService;
        }

        public async Task<IActionResult> MyPoints()
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var userVM = this.db.UserInfos.Where(x => x.UserId == user.Id).Select(x => new SyrveysListViewModel
            {
                Points = x.Points,
                Surveys = x.SurveyUserInfos
                .Select(s => new SurveysNamePoints
                {
                    Name = s.Survey.Name,
                    Points = s.isComplete == true ? s.Survey.PointsTotal : s.Survey.PointsStart,
                    Date = s.Survey.ModifiedOn.HasValue ? s.Survey.ModifiedOn.Value.ToString("dd.MM.yyyy", CultureInfo.InvariantCulture) : null,
                }),
                VouchersUser = x.VoucherUsers.Select(v => new VoucherViewModel {
                Name = v.Voucher.Name,
                Points = v.Voucher.Points,
                })
                .ToList(),
            }).FirstOrDefault();

            if (userVM != null)
            {
                return this.View(userVM);
            }
            else
            {
                return this.Redirect("Create");
            }
        }

        public IActionResult CollectPoints()
        {
            var userId = this.userManager.GetUserId(this.User);
            //var userInfo = this.userInfosRepository.All().FirstOrDefault(x => x.UserId == userId);
            var userInfo = this.db.UserInfos.FirstOrDefault(x => x.UserId == userId);

            if (userInfo != null)
            {
                var viewModel = new SyrveysListViewModel();
                viewModel.SurveysForUser = this.userInfosService.GetSurveysForUser(userId);
                return this.View(viewModel);
            }
            else
            {
                return this.Redirect("Create");
            }
        }

        public IActionResult Create()
        {
            var viewModel = new CreateUserInfoInputModel();
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserInfoInputModel input)
        {
            var userId = this.userManager.GetUserId(this.User);
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            try
            {
                await this.userInfosService.CreateAsync(input, userId);
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                return this.View(input);
            }

            return this.Redirect("MyPoints");
        }

        public IActionResult Buy(int id)
        {
            var userId = this.userManager.GetUserId(this.User);
            var userInfo = this.db.UserInfos.FirstOrDefault(x => x.UserId == userId);
            var voucher = this.db.Vouchers.FirstOrDefault(x => x.Id == id);
            userInfo.Points -= voucher.Points;
            var voucherUser = new VoucherUser
            {
                VoucherId = voucher.Id,
                UserInfoId = userInfo.Id,
            };
            userInfo.VoucherUsers.Add(voucherUser);
            this.db.SaveChangesAsync();

            this.TempData["Message"] = "Успешно поръчахте този ваучер";
            return this.Redirect("/UserInfos/MyPoints");
        }
    }
}

Web/SayOnlinePanel.Web/Controllers/VouchersController.cs
namespace SayOnlinePanel.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using SayOnlinePanel.Data;
    using SayOnlinePanel.Data.Models;
    using SayOnlinePanel.Services.Data;
    using SayOnlinePanel.Web.ViewModels.Vouchers;

    public class VouchersController : Controller
    {
        private readonly IVouchersService vouchersService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IUserInfosService userInfosService;
        private readonly ApplicationDbContext db;

        public VouchersController(IVouchersService vouchersService, UserManager<ApplicationUser> userManager, IUserInfosService userInfosService, ApplicationDbContext db)
        {
            this.vouchersService = vouchersService;
            this.userManager = userManager;
            this.userInfosService = userInfosService;
            this.db = db;
        }

        public IActionResult All()
        {
            var viewModel = new AllVouchersViewModel();

            var vouchers = this.vouchersService.GetAll<VoucherViewModel>();
            viewModel.Vouchers = vouchers;

            return this.View(viewModel);
        }

        public IActionResult ById(int id)
        {
            var voucherViewModel = this.vouchersService.GetById<VoucherViewModel>(id);
            if (voucherViewModel == null)
            {
                return this.NotFound();
            }

            var userid = this.userManager.GetUserId(this.User);
            if (userid == null)
            {
                this.ViewData["userPoints"] = 0;
            }
            else
            {
                //var userPoints = this.userInfosService.GetUsersPointsForVoucher(userid);
                var userPoints = this.db.UserInfos.FirstOrDefault(x => x.UserId == userid).Points;

                this.ViewData["userPoints"] = userPoints;
            }

            return this.View(voucherViewModel);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            var viewModel = new CreateVoucherInputModel();
            return this.View(viewModel);
        }

        [Authorize(Roles = "Administrator")]
        [HttpPost]
        public async Task<IActionResult> Create(CreateVoucherInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.vouchersService.CreateAsync(input);

            this.TempData["Message"] = "Voucher added successfully.";
            return this.Redirect("All");
        }
    }
}

Web/SayOnlinePanel.Web/Views/Shared/_Layout.cshtml
@using SayOnlinePanel.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/Likert.css" rel="stylesheet" asp-append-version="true" />

    <script src="~/js/highcharts.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse" id="navbarColor01">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">

                        @if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Administration</a>
                                <div class="dropdown-menu">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="TargetSurveys" asp-action="Create">Create Target Survey</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="TargetSurveys" asp-action="TargetSurveys">Target Surveys List</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Surveys" asp-action="Surveys">Surveys List</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Vouchers" asp-action="Create">Create Voucher</a>
                                    <div class="dropdown-divider"></div>
                                </div>
                            </li>
                        }

                        <li class="nav-item active">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vouchers" asp-action="All">Награди</a>
                        </li>
                       
                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item active">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserInfos" asp-action="CollectPoints">Събери точки</a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserInfos" asp-action="MyPoints">Моите точки</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>
    
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/SayOnlinePanel.Web/Views/Shared/_PagingPartial.cshtml
@model PagingViewModel
<nav aria-label="...">
    <ul class="pagination justify-content-center">
        <li class="page-item @if (!Model.HasPreviousPage) { <text>disabled</text> }">
            <a class="page-link" asp-action="All" asp-route-id="@Model.PreviousPageNumber">Previous</a>
        </li>
        @for (int i = Model.PageNumber - 4; i < Model.PageNumber; i++)
        {
            if (i > 0)
            {
                <li class="page-item"><a class="page-link" asp-action="All" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item active" aria-current="page">
            <span class="page-link">
                @Model.PageNumber
                <span class="sr-only">(current)</span>
            </span>
        </li>
        @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 4; i++)
        {
            if (i <= Model.PagesCount)
            {
                <li class="page-item"><a class="page-link" asp-action="All" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item @if (!Model.HasNextPage) { <text>disabled</text> }">
            <a class="page-link" asp-action="Surveys" asp-route-id="@Model.NextPageNumber">Next</a>
        </li>
    </ul>
</nav>