Web/SayOnlinePanel.Web/Controllers/StaticticsController.cs
namespace SayOnlinePanel.Web.Controllers
{
    using System.Linq;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using SayOnlinePanel.Data;
    using SayOnlinePanel.Data.Models;
    using SayOnlinePanel.Services.Data;
    using SayOnlinePanel.Web.ViewModels.Statictics;

    [Authorize(Roles = "Administrator")]
    public class StaticticsController : Controller
    {
        private readonly ISurveyService surveyService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ApplicationDbContext db;

        public StaticticsController(ISurveyService surveyService, UserManager<ApplicationUser> userManager, ApplicationDbContext db)
        {
            this.surveyService = surveyService;
            this.userManager = userManager;
            this.db = db;
        }

        public IActionResult ByIdStatistics(int id)
        {
            var survey = this.db.UserAnswers.Where(x => x.SurveyId == id).Select(x => new SingleSurveyViewModel
            {
                Name = x.Survey.Name,
                Questions = x.Survey.Questions.Select(s => new QuestionsViewModel
                {
                    Id = s.Id,
                    Name = s.Name,
                    QuestionType = s.QuestionType,
                    Answers = s.Answers.Select(a => new AnswersViewModel
                    {
                        Name = a.Name,
                        Count = a.UserAnswers.Count(),
                        CountPercent = (double)a.UserAnswers.Count() / (double)s.Survey.SampleTotal * 100,
                    }).ToList(),
                }).ToList(),
            }).FirstOrDefault();

            return this.View(survey);
        }

        public IActionResult SampleComplete(int id)
        {
            var survey = this.db.UserAnswers.Where(x => x.SurveyId == id).Select(x => new CompleteModel
            {
                Name = x.Survey.Name,
                SampleTotalComplete = x.Survey.SampleTotalComplete,
                SampleTotal = x.Survey.SampleTotal,
                SampleTotalCompletePercent = ((double)x.Survey.SampleTotalComplete / (double)x.Survey.SampleTotal) * 100,
                SampleMaleComplete = x.Survey.SampleMaleComplete,
                SampleMale = x.Survey.SampleMale,
                SampleMaleCompletePercent = x.Survey.SampleMale > 0 ? ((double)x.Survey.SampleMaleComplete / (double)x.Survey.SampleMale) * 100 : 0,
                SampleFemaleComplete = x.Survey.SampleFemaleComplete,
                SampleFemaleCompletePercent = x.Survey.SampleFemale > 0 ? ((double)x.Survey.SampleFemaleComplete / (double)x.Survey.SampleFemale) * 100 : 0,
                SampleFemale = x.Survey.SampleFemale,
            }).FirstOrDefault();

            int completeTotal = this.db.UserAnswers.Where(x => x.SurveyId == id).Select(x => x.Survey.SampleTotalComplete).FirstOrDefault();
            int sampleTotal = this.db.UserAnswers.Where(x => x.SurveyId == id).Select(x => x.Survey.SampleTotal).FirstOrDefault();
            return this.View(survey);
        }
    }
}

Web/SayOnlinePanel.Web/Controllers/SurveysController.cs
namespace SayOnlinePanel.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;
    using SayOnlinePanel.Services.Data;
    using SayOnlinePanel.Web.ViewModels.Surveys;

    [Authorize(Roles = "Administrator")]
    public class SurveysController : Controller
    {
        private readonly ISurveyService surveyService;
        private readonly IWebHostEnvironment environment;

        public SurveysController(ISurveyService surveyService, IWebHostEnvironment environment)
        {
            this.surveyService = surveyService;
            this.environment = environment;
        }

        public IActionResult Create()
        {
            var viewModel = new CreateSurveyInputModel();
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateSurveyInputModel input, int id)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            try
            {
                await this.surveyService.CreateAsync(input, id);
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                return this.View(input);
            }

            this.TempData["Message"] = "Survey added successfully.";
            return this.Redirect("/Surveys/Surveys");
        }

        public IActionResult Surveys(int id = 1)
        {
            if (id <= 0)
            {
                return this.NotFound();
            }

            const int ItemsPerPage = 12;
            var viewModel = new SyrveysListViewModel
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = id,
                SurveysCount = this.surveyService.GetCount(),
                Surveys = this.surveyService.GetAll<SurveyInListViewModel>(id, ItemsPerPage),
            };
            return this.View(viewModel);
        }

        public IActionResult ById(int id)
        {
            var survey = this.surveyService.GetById<SingleSurveyViewModel>(id);
            return this.View(survey);
        }

        public IActionResult Edit(int id)
        {
            var inputModel = this.surveyService.GetById<EditSurveyInputModel>(id);
            return this.View(inputModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditSurveyInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            try
            {
                await this.surveyService.UpdateAsync(id, input);
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                return this.View(input);
            }

            return this.RedirectToAction(nameof(this.ById), new { id });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await this.surveyService.DeleteAsync(id);
            return this.RedirectToAction(nameof(this.Surveys));
        }
    }
}

Web/SayOnlinePanel.Web/Views/Surveys/ById.cshtml
@model SayOnlinePanel.Web.ViewModels.Surveys.SingleSurveyViewModel
<h3>@Model.Name</h3>

<div>
    @foreach (var question in Model.Questions)
    {
        <label>@question.Name</label>

        @if (question.QuestionType.ToString() == "SingleAnswer")
        {
            @foreach (var answer in question.Answers)
            {
                <div class="form-check">
                    <label class="form-check-label">
                        <input type="radio" class="form-check-input">
                        @answer.Name
                    </label>
                </div>}}
        @if (question.QuestionType.ToString() == "MultipleAnswer")
        {
            @foreach (var answer in question.Answers)
            {
                <div class="form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" type="checkbox" value="">
                        @answer.Name
                    </label>
                </div>}}
        @if (question.QuestionType.ToString() == "LikertScales")
        {
            <form action="">
                <div class="wrap">
                    <ul class='likert'>
                        @foreach (var answer in question.Answers)
                        {
                            <li>
                                <input type="radio" name="likert" value="strong_agree">
                                <label>@answer.Name</label>
                            </li>
                        }
                    </ul>
                </div>
            </form>}
        @if (question.QuestionType.ToString() == "Dichotomous")
        {
            <div class="form-group">
                <select class="form-control">
                    @foreach (var answer in question.Answers)
                    {
                        <option>@answer.Name</option>
                    }
                </select>
            </div>}
        @if (question.QuestionType.ToString() == "OpenEnded")
        {
            <div class="form-group">
                <label for="exampleTextarea"></label>
                <textarea class="form-control" rows="2"></textarea>
            </div>}
        @if (question.QuestionType.ToString() == "Quantitative")
        {
            <div class="form-group">
                <label for="exampleTextarea"></label>
                <input class="form-control" type="number" rows="1">
            </div>}
        <hr />}


    <div class="row">
        <a asp-controller="Surveys" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-outline-warning" style="margin-right: 10px">Edit</a>
        <form method="post" asp-controller="Surveys" asp-action="Delete" id="deleteForm" asp-route-id="@Model.Id">
        </form>
        <button class="btn btn-outline-danger" data-toggle="modal" data-target="#deleteModal">Delete</button>
    </div>

    <div class="modal" tabindex="-1" role="dialog" id="deleteModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <p>Do you want to delete "@Model.Name"?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" onclick="deleteForm.submit()">Yes</button>
                    <button type="button" class="btn btn-success" data-dismiss="modal">No</button>
                </div>
            </div>
        </div>
    </div>
</div>
<p>&nbsp;</p>
<p>&nbsp;</p>

Web/SayOnlinePanel.Web/Views/Surveys/Create.cshtml
@using SayOnlinePanel.Data.Models
@model SayOnlinePanel.Web.ViewModels.Surveys.CreateSurveyInputModel

@{ var questionTypesList = Enum.GetValues(typeof(QuestionType)).OfType<QuestionType>().Select(m => m.ToString()).ToList(); }
<h3>Create New Survey</h3>

<form method="post">
    <h1>@this.ViewData["Title"]</h1>
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control" rows="2"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="StartDate"></label>
        <input asp-for="StartDate" class="form-control" />
        <span asp-validation-for="StartDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="EndDate"></label>
        <input asp-for="EndDate" class="form-control" />
        <span asp-validation-for="EndDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="PointsStart"></label>
        <input asp-for="PointsStart" class="form-control" />
        <span asp-validation-for="PointsStart" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="PointsTotal"></label>
        <input asp-for="PointsTotal" class="form-control" />
        <span asp-validation-for="PointsTotal" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="SampleTotal"></label>
        <input asp-for="SampleTotal" class="form-control" />
        <span asp-validation-for="SampleTotal" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="SampleFemale"></label>
        <input asp-for="SampleFemale" class="form-control" />
        <span asp-validation-for="SampleFemale" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="SampleMale"></label>
        <input asp-for="SampleMale" class="form-control" />
        <span asp-validation-for="SampleMale" class="text-danger"></span>
    </div>

    <div id="QuestionsContainer" class="form-group">
            <label asp-for="Questions"></label>
            <a id="addQ" class="btn btn-outline-secondary">Add Question</a>
            <div id="Q" class="form-group"></div>
    </div>

    <input type="submit" class="btn btn-primary" />
</form>

<hr />
<p>&nbsp;</p>



@section Scripts {
    <script>
        let btnQ = document.querySelector("#addQ");
        let divQ = document.querySelector("#Q");
        btnQ.addEventListener("click", AddQuestion);
        let questionIndex = 0;
        function AddQuestion() {
            this.remove();
            if (document.getElementById("AddABtn") != null) {
                document.getElementById("AddABtn").remove()
            }
            let p = createHTMLElement("p", `${questionIndex + 1}`);
            let divQname = createHTMLElement("div");
            let nameQ = createHTMLElement("input", null, "form-control", [{ k: "placeholder", v: "Question text" }]);
            nameQ.style.marginBottom = "10px";
            nameQ.name = `Questions[${questionIndex}].Name`;
            divQname.appendChild(nameQ);          

            let divQType = createHTMLElement("div");
            let typeQ = createHTMLElement("select", null, "form-control", [{ k: "placeholder", v: "Question type" }]);
            typeQ.style.marginBottom = "10px";
            let options = @Html.Raw(Json.Serialize(questionTypesList));

            for (let index = 0; index < options.length; index++) {
                let opt = options[index];
                let el = document.createElement('option');
                el.textContent = String(opt);
                el.value = String(opt);
                typeQ.appendChild(el);
            }

            typeQ.name = `Questions[${questionIndex}].QuestionType`;

            divQType.appendChild(typeQ);

            let AddABtn = createHTMLElement("a", "Add Answer", "btn");
            AddABtn.id = "AddABtn";
            AddABtn.classList.add('btn-outline-success');
            AddABtn.style.marginBottom = "10px";
            let divA = document.createElement('div');
            divQ.appendChild(p);
            divQ.appendChild(divQname);
            divQ.appendChild(divQType);
            divQ.appendChild(AddABtn);
            divQ.appendChild(divA);
            let answerIndex = 0;

            AddABtn.addEventListener("click", () => {
                let nameA = createHTMLElement("input", null, "form-control", [{ k: "placeholder", v: "Answer text" }]);
                nameA.style.marginBottom = "10px";
                nameA.name = `Questions[${questionIndex - 1}].Answers[${answerIndex}].Name`;

                divA.appendChild(nameA);
                let divQbtn = document.createElement('div');
                divQbtn.appendChild(btnQ);
                divA.appendChild(divQbtn);

                answerIndex++;
            })
            questionIndex++;
        }

        function createHTMLElement(tagName, textContent, className, attributes, event) {
            let elm = document.createElement(tagName);
            if (className) {
                elm.classList.add(className);
            }
            if (textContent) {
                elm.textContent = textContent;
            }
            if (attributes) {
                attributes.forEach((a) => elm.setAttribute(a.k, a.v));
            }
            if (event) {
                elm.addEventListener(event.name, event.func)
            }
            return elm;
        }
    </script>
}

Web/SayOnlinePanel.Web/Views/Surveys/Edit.cshtml
@using SayOnlinePanel.Data.Models
@model SayOnlinePanel.Web.ViewModels.Surveys.EditSurveyInputModel

@{
    var questionTypesList = Enum.GetValues(typeof(QuestionType)).OfType<QuestionType>().Select(m => new { Text = m.ToString(), Value = (int)m }).ToList();
}

<form method="post" id="editForm">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="StartDate"></label>
        <input asp-for="StartDate" class="form-control" />
        <span asp-validation-for="StartDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="EndDate"></label>
        <input asp-for="EndDate" class="form-control" />
        <span asp-validation-for="EndDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="PointsStart"></label>
        <input asp-for="PointsStart" class="form-control" />
        <span asp-validation-for="PointsStart" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="PointsTotal"></label>
        <input asp-for="PointsTotal" class="form-control" />
        <span asp-validation-for="PointsTotal" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="SampleTotal"></label>
        <input asp-for="SampleTotal" class="form-control" />
        <span asp-validation-for="SampleTotal" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="SampleMale"></label>
        <input asp-for="SampleMale" class="form-control" />
        <span asp-validation-for="SampleMale" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="SampleFemale"></label>
        <input asp-for="SampleFemale" class="form-control" />
        <span asp-validation-for="SampleFemale" class="text-danger"></span>
    </div>
    <div class="form-group">
        <hr />
        @for (var i = 0; i < Model.Questions.Count(); i++)
        {

            @Html.HiddenFor(x => Model.Questions[i].Id)
            <div class="form-group">
                @Html.LabelFor(x => Model.Questions[i].Name, "Question Text:")
                @Html.TextBoxFor(x => Model.Questions[i].Name, new { @class = "form-control" })

                @Html.LabelFor(x => Model.Questions[i].QuestionType)
                @*@Html.TextBoxFor(x => Model.Questions[i].QuestionType, new { @class = "form-control", @readonly = "readonly" })*@
                @Html.DropDownListFor(x => Model.Questions[i].QuestionType, new SelectList(questionTypesList, "Value", "Text", Model.Questions[i].QuestionType))
                @*@Html.TextBoxFor(x => Model.Questions[i].QuestionType, new { @class = "form-control" })*@

                @for (var j = 0; j < Model.Questions[i].Answers.Count(); j++)
                {

                    @Html.HiddenFor(x => Model.Questions[i].Answers[j].Id)
                    <div class="form-group">
                        @Html.LabelFor(x => Model.Questions[i].Answers[j].Name, "Answer Text:")
                        @Html.TextBoxFor(x => Model.Questions[i].Answers[j].Name, new { @class = "form-control" })

                    </div>
                }
            </div>
            <hr />
        }
    </div>
    <hr />
    <input type="hidden" asp-for="Id" />
</form>

<button type="submit" class="btn btn-success" data-toggle="modal" data-target="#modalEdit">Save changes</button>

<hr />
<p>&nbsp;</p>




<!-- Modal -->
<div class="modal" id="modalEdit" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Confirm edit</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>
                    Do you confirm this changes?
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="editForm.submit()">Save changes</button>
            </div>
        </div>
    </div>
</div>

Web/SayOnlinePanel.Web/Views/Surveys/Surveys.cshtml
@using SayOnlinePanel.Common
@model SayOnlinePanel.Web.ViewModels.Surveys.SyrveysListViewModel
@{
    this.ViewData["Title"] = "All Surveys, page " + Model.PageNumber;
}

<h3>@this.ViewData["Title"]</h3>
<hr />

<div class="list-group">
    @foreach (var sv in Model.Surveys)
    {
        <div class="list-group-item list-group-item-action flex-column align-items-start active"><h5 class="mb-1">@sv.Name</h5></div>
        <div style="margin-top: 10px">
            <a asp-action="ById" asp-route-id="@sv.Id" class="btn btn-outline-primary">View</a>
            <a asp-controller="Statictics" asp-action="SampleComplete" asp-route-id="@sv.Id" class="btn btn-outline-secondary">Complete Sample</a>
            <a asp-controller="Statictics" asp-action="ByIdStatistics" asp-route-id="@sv.Id" class="btn btn-outline-info">Charts</a>
        </div>
        <div class="d-flex w-100 justify-content-between">
            <small style="margin-top: 10px">Start: @sv.StartDate.Date.ToString("d")   /   End: @sv.EndDate.Date.ToString("d")</small>
            <p>&nbsp;</p>
        </div>
        <p>&nbsp;</p>
    }
</div>
<partial name="_PagingPartial" model="@Model" />
<p>&nbsp;</p>